public enum eGWalletCompletionStatus
{
	GWALLET_SUCCESS = 0,
	GWALLET_ERROR_NO_SHARED_STORAGE = 1,
	GWALLET_ERROR_NO_GMAIL_CREDENTIAL = 2,
	GWALLET_ERROR_INVALID_SHARED_DATA = 3,
	GWALLET_ERROR_BUSY = 4,
	GWALLET_ERROR_NEGATIVE_BALANCE = 5,
	GWALLET_ERROR_INVALID_VERSION_PAST = 6,
	GWALLET_ERROR_INVALID_VERSION_FUTURE = 7,
	GWALLET_ERROR_DEVICE_OFFLINE = 8,
	GWALLET_ERROR_FROM_SERVER = 9,
	GWALLET_ERROR_MISSING_REQUIRED_FIELD = 10,
	GWALLET_ERROR_CUSTOMER_SUPPORT = 11,
	GWALLET_ERROR_NOT_INITIALIZED = 12,
	GWALLET_ERROR_NOT_LOADED = 13,
	GWALLET_ERROR_NOT_SUBSCRIBER = 14,
	GWALLET_ERROR_UNKNOWN = 15
}
